// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuM7WbX5tTm44c_tV5aQ-IOUpdZUanoYo',
    appId: '1:974281981376:web:7e13056aee902b972b1c25',
    messagingSenderId: '974281981376',
    projectId: 'fir-practice-3ad5b',
    authDomain: 'fir-practice-3ad5b.firebaseapp.com',
    storageBucket: 'fir-practice-3ad5b.firebasestorage.app',
    measurementId: 'G-PHRT43E42J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzZSltESA1ElvqrOFhbhv2fBgtKGwkvM8',
    appId: '1:974281981376:android:bebaf70c493147a12b1c25',
    messagingSenderId: '974281981376',
    projectId: 'fir-practice-3ad5b',
    storageBucket: 'fir-practice-3ad5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXLwqeBwTgRT-kZLzOdw_IIOrq5TrfzAA',
    appId: '1:974281981376:ios:a0cf66991bdb17a82b1c25',
    messagingSenderId: '974281981376',
    projectId: 'fir-practice-3ad5b',
    storageBucket: 'fir-practice-3ad5b.firebasestorage.app',
    iosBundleId: 'com.umartech.firebasePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXLwqeBwTgRT-kZLzOdw_IIOrq5TrfzAA',
    appId: '1:974281981376:ios:a0cf66991bdb17a82b1c25',
    messagingSenderId: '974281981376',
    projectId: 'fir-practice-3ad5b',
    storageBucket: 'fir-practice-3ad5b.firebasestorage.app',
    iosBundleId: 'com.umartech.firebasePractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuM7WbX5tTm44c_tV5aQ-IOUpdZUanoYo',
    appId: '1:974281981376:web:78cdab6ee579ac0b2b1c25',
    messagingSenderId: '974281981376',
    projectId: 'fir-practice-3ad5b',
    authDomain: 'fir-practice-3ad5b.firebaseapp.com',
    storageBucket: 'fir-practice-3ad5b.firebasestorage.app',
    measurementId: 'G-KBYVMJHPHV',
  );
}
